import { Medicine } from '../types/medicine';
import { ReminderLog } from '../types/reminder';
import { getTodayDateString } from './dateUtils';

export const INITIAL_DEMO_MEDICINES: Medicine[] = [
  {
    id: 'demo-med-1',
    name: 'Vitamin D3',
    type: 'capsule',
    dosageAmount: 1,
    dosageUnit: 'Capsule',
    frequency: 'once_daily',
    times: ['08:00'],
    startDate: '2026-09-01',
    endDate: null,
    instructions: 'Take 1 capsule in the morning with water after breakfast.',
    notes: 'Doctor recommended for daily bone health support.',
    enableStockTracking: true,
    currentStock: 24,
    dailyUsage: 1,
    lowStockThreshold: 5,
    active: true,
    createdAt: '2026-09-01T08:00:00.000Z',
    updatedAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'demo-med-2',
    name: 'Amoxicillin',
    type: 'tablet',
    dosageAmount: 500,
    dosageUnit: 'mg',
    frequency: 'twice_daily',
    times: ['08:00', '20:00'],
    startDate: '2026-09-05',
    endDate: '2026-09-15',
    instructions: 'Take with or without food. Complete the full antibiotic course.',
    notes: 'Prescribed for sinus infection.',
    enableStockTracking: true,
    currentStock: 12,
    dailyUsage: 2,
    lowStockThreshold: 4,
    active: true,
    createdAt: '2026-09-05T10:00:00.000Z',
    updatedAt: '2026-09-05T10:00:00.000Z',
  },
  {
    id: 'demo-med-3',
    name: 'Metformin',
    type: 'tablet',
    dosageAmount: 1,
    dosageUnit: 'Tablet',
    frequency: 'twice_daily',
    times: ['08:30', '19:30'],
    startDate: '2026-08-01',
    endDate: null,
    instructions: 'Take with meals to reduce stomach upset.',
    notes: 'Blood glucose management.',
    enableStockTracking: true,
    currentStock: 4,
    dailyUsage: 2,
    lowStockThreshold: 7, // Low stock warning!
    active: true,
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-08-01T00:00:00.000Z',
  },
  {
    id: 'demo-med-4',
    name: 'Eye Drops (Artificial Tears)',
    type: 'drops',
    dosageAmount: 2,
    dosageUnit: 'Drops',
    frequency: 'thrice_daily',
    times: ['09:00', '14:00', '21:00'],
    startDate: '2026-09-01',
    endDate: null,
    instructions: 'Instill 2 drops in each eye for dryness relief.',
    notes: 'Keep bottle cap clean.',
    enableStockTracking: false,
    currentStock: 0,
    dailyUsage: 6,
    lowStockThreshold: 5,
    active: true,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  }
];

export const INITIAL_DEMO_HISTORY: ReminderLog[] = [
  {
    id: 'demo-hist-1',
    medicineId: 'demo-med-1',
    medicineName: 'Vitamin D3',
    medicineType: 'capsule',
    dosage: '1 Capsule',
    scheduledDate: getTodayDateString(),
    scheduledTime: '08:00',
    status: 'taken',
    takenAt: `${getTodayDateString()}T08:03:00.000Z`,
    createdAt: `${getTodayDateString()}T08:03:00.000Z`,
  },
  {
    id: 'demo-hist-2',
    medicineId: 'demo-med-2',
    medicineName: 'Amoxicillin',
    medicineType: 'tablet',
    dosage: '500 mg',
    scheduledDate: getTodayDateString(),
    scheduledTime: '08:00',
    status: 'taken',
    takenAt: `${getTodayDateString()}T08:05:00.000Z`,
    createdAt: `${getTodayDateString()}T08:05:00.000Z`,
  },
  {
    id: 'demo-hist-3',
    medicineId: 'demo-med-3',
    medicineName: 'Metformin',
    medicineType: 'tablet',
    dosage: '1 Tablet',
    scheduledDate: getTodayDateString(),
    scheduledTime: '08:30',
    status: 'taken',
    takenAt: `${getTodayDateString()}T08:32:00.000Z`,
    createdAt: `${getTodayDateString()}T08:32:00.000Z`,
  }
];
